name: colla_chat
description: colla_chat Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 系统功能，获取系统信息和操作，需要调用插件才能完成
  flutter_background: ^1.1.0
  flutter_background_service: ^2.4.5
  path_provider: ^2.0.11
  image_picker: ^0.8.7 #选取图库
  advance_image_picker: ^0.1.7+1
  url_launcher: ^6.1.6 #打开系统浏览器
  open_file: ^3.2.1 #打开文件, 和最新device_info有版本冲突

  camera_windows: ^0.2.1+2
  camera_web: ^0.3.1+3
  wechat_camera_picker: ^3.7.0
  photo_manager: ^2.5.2
  screenshot: ^1.2.3
  images_picker: ^1.2.11
  orientation: ^1.2.0 # 控制屏幕旋转
  geolocator: ^9.0.2
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0
  network_info_plus: ^3.0.1
  beamer: ^1.4.1+1
  sensors_plus: ^2.0.1
  battery_plus: ^3.0.2
  flutter_contacts: ^1.1.4
  connectivity_plus: ^3.0.0
  flutter_nearby_connections: ^1.1.1
  mimecon: ^0.0.2

  # 存储
  shared_preferences: ^2.0.10
  flutter_secure_storage: ^8.0.0
  sqlite3: ^1.7.1
  sqlite3_flutter_libs: ^0.5.7
  idb_shim: ^2.0.1

  #网络
  flutter_webrtc: ^0.9.24
  dart_webrtc: ^1.0.12
  #flutter_web_auth: ^0.4.0  #macos有问题
  dio: ^5.0.2
  dio_http2_adapter: ^2.1.0
  web_socket_channel: ^2.2.0
  #cached_network_image: ^3.0.0
  telephony: 0.2.0

  #界面
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  fluttericon: ^2.0.0
  flutter_animated_icons: ^1.0.0
  country_pickers: ^2.0.0
  country_picker: ^2.0.15
  #international_phone_input: ^1.0.4
  phone_numbers_parser: ^7.0.0+1
  font_awesome_flutter: ^10.1.0
  flushbar: ^1.10.4
  #share: ^0.6.5
  flutter_emoji: ^2.2.1+1
  emoji_picker_flutter: ^1.3.1
  animated_bottom_navigation_bar: ^1.1.0+1
  flutter_animate: ^4.1.0
  fluro: ^2.0.3
  flutter_multi_formatter: ^2.5.1
  #flutter_awesome_select: ^6.5.0
  #awesome_select: ^6.0.0
  #multi_select_flutter: ^4.1.2
  chips_choice: ^3.0.0
  phone_number: ^1.0.0
  #sim_info: ^0.1.3
  phone_form_field: ^7.0.5
  #flutter-international-phone-input:
  intl_phone_field: ^3.1.0
  mobile_number: ^2.1.1
  badges: ^3.0.2
  extended_list: any
  glassmorphism: ^3.0.0
  glass_kit: ^2.0.1
  #flui: 0.9.2
  syncfusion_flutter_datagrid: ^20.2.36
  pluto_grid: ^6.0.1
  data_table_2: any
  file_saver: ^0.1.0
  #pluto_grid_export: ^1.0.2
  flutter_neumorphic: ^3.2.0
  fl_chart: ^0.61.0
  fluttertoast: ^8.2.1
  extended_text: ^10.0.1 #文本扩展显示
  extended_text_field: ^11.0.1 #文字表情混入
  extended_text_library: ^10.0.0 #Flutter2.5用这个,,其他可注释
  azlistview: ^2.0.0 #特殊列表滑动
  # flutter_echarts: ^2.4.0
  fluent_ui: 4.4.0
  macos_ui: ^1.11.1
  flutter_material_color_picker: ^1.1.0+2
  animated_text_kit: ^4.2.1
  after_layout: ^1.1.0
  snapping_sheet: ^3.1.0

  #flutter_bloc: ^6.1.0
  #flutter_swiper: 1.1.6 # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  #flutter_swiper_null_safety: any
  card_swiper: ^2.0.4
  flutter_screenutil: ^5.5.3 # Flutter 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil

  flex_color_scheme: ^6.1.2
  file_selector: ^0.9.2+2
  filesystem_picker: ^3.1.0
  wechat_assets_picker: ^8.4.0 #微信图库
  full_picker: ^1.1.5
  flutter_slidable: ^2.0.0
  flutter_drawing_board: ^0.4.4+2
  custom_pop_up_menu: ^1.2.4
  #popup_menu: ^1.0.5
  star_menu: ^3.1.0+1
  flutter_floating_bottom_bar: ^1.1.0
  focused_menu: ^1.0.5
  floating_action_bubble: ^1.1.4
  expandable: ^5.0.1
  #安全加密
  cryptography: ^2.0.5 #ecc,aes
  #在macos上不能使用，error: cannot call value of non-function type 'FlutterBinaryMessenger'
  #cryptography_flutter: ^2.0.2
  bs58: ^1.0.2
  webcrypto: ^0.5.3
  pinenacl: ^0.5.1
  encrypt: ^5.0.1 #aes
  openpgp: ^3.2.8 #rsa,sha
  libsignal_protocol_dart: ^0.6.5
  crypto: ^3.0.1 #sha
  archive: any
  uuid: 3.0.7
  local_auth: any

  #基本开发工具
  xml: ^6.0.1
  mime: ^1.0.2
  flutter_keyboard_visibility: ^5.4.0
  keyboard_actions: ^4.1.0
  synchronized: ^3.0.0+2
  flutter_smart_dialog: ^4.9.0+1
  pdfx: ^2.3.0
  #pdf_flutter: ^1.1.4
  pdf: ^3.8.3
  #syncfusion_flutter_pdfviewer: ^20.3.49
  json_annotation: ^4.3.0
  permission_handler: ^10.0.0 #权限处理1
  provider: ^6.0.1 #状态管理
  pull_to_refresh_notification: ^3.0.0
  share_plus: ^6.3.0
  receive_sharing_intent: ^1.4.5
  date_format: ^2.0.6
  omni_datetime_picker: ^1.0.1
  toggle_switch: ^2.0.1
  classic_logger: any
  logger: ^1.1.0
  #logging: ^1.0.2
  cross_file: any
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  qr: ^3.0.1
  #barcode: ^2.2.3
  #barcode_image: ^2.0.2
  #barcode_widget: ^2.0.2
  barcode_scan2: ^4.2.4
  #mobile_scanner: ^2.0.0  #macos有问题
  lpinyin: ^2.0.3 #拼音

  window_manager: any
  #有特殊安装要求，否则编译出错
  #webview_windows: ^0.2.2
  #flutter_inappwebview: ^6.0.0-beta.22
  flutter_inappwebview: ^5.7.2+3
  #flutter_webview_pro: ^3.0.1+4
  #easy_web_view: ^1.6.0

  # 多媒体
  #flutter_audio_waveforms: any
  photo_view: ^0.14.0 #图片显示
  #音频处理 ios:Just add those 2 flags in XCode > Build Settings > Other Linker Flags :
  #-lc++
  #-lstd++
  flutter_sound: ^9.2.13
  audioplayers: ^3.0.1 #音频处理,所有平台
  audioplayers_platform_interface: ^4.0.0
  audioplayers_windows: ^1.1.3
  another_audio_recorder: ^1.0.1
  assets_audio_player: ^3.0.6
  audiofileplayer: ^2.1.1
  record_mp3: ^3.0.0
  audio_waveforms: ^1.0.1
  video_player_web: ^2.0.15
  flick_video_player: ^0.5.0 #video_player的封装
  appinio_video_player: ^1.2.0 #video_player的封装
  video_player: ^2.6.0 #mobile and web
  video_player_win: ^2.2.0
  video_player_macos: ^1.0.6
  video_player_control_panel: ^1.1.0
  dart_vlc: ^0.4.0
  chewie: ^1.3.6 #video_player的封装
  better_player: ^0.0.83 #chewie的封装
  fijkplayer: ^0.10.1 #mobile
  flutter_vlc_player: ^7.1.5 #video_player的替代，mobile
  record: ^4.4.3
  just_audio: ^0.9.30
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.4
  just_waveform: ^0.0.4
  audio_service: ^0.18.9
  just_audio_background: ^0.0.1-beta.9
  audio_session: ^0.1.13
  flutter_tts: ^3.5.3
  speech_to_text: any
  flutter_image_compress: ^1.0.0-nullsafety #图片压缩1
  video_thumbnail: ^0.5.2
  image_gallery_saver: ^1.7.1
  extended_image: ^7.0.2
  extended_image_library: ^3.4.1
  image_editor: ^1.3.0
  image: ^4.0.12
  flutter_luban: ^0.1.13
  #image_cropping: ^0.0.13 #裁剪图片
  crop_your_image: ^0.7.4

  #应用
  flutter_filereader: 3.0.0
  i18n_extension: ^8.0.0
  html_editor_enhanced: ^2.5.1
  #  flutter_quill: 6.2.2
  #git: https://github.com/singerdmx/flutter-quill.git
  #  flutter_quill_extensions: ^0.1.0
  #git: https://github.com/singerdmx/flutter-quill.git/flutter_quill_extensions
  #  visual_editor:
  #    git: https://github.com/visual-space/visual-editor.git
  #youtube_player_flutter_quill: ^8.2.2
  flutter_rte: ^0.4.9
  universal_html: ^2.0.8
  enough_mail: ^2.1.0
  enough_media: ^2.2.0
  enough_mail_html: ^2.0.0
  enough_html_editor: ^0.0.5
  #在ios下会引发启动崩溃
  #enough_mail_flutter: ^2.0.0 #ios崩溃
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  backdrop: ^0.8.1 #Use BackdropScaffold instead of the standard Scaffold in your app
  sliding_up_panel: ^2.0.0+1
  material_floating_search_bar: ^0.3.7
  google_maps_flutter: ^2.2.1
  #google_map_location_picker: ^4.1.7
  map_launcher: ^2.4.0 #Map Launcher is a flutter plugin to find available maps installed on a device and launch them
  flutter_svg: ^2.0.3
  apple_maps_flutter: ^1.2.0
  platform_maps_flutter: ^1.0.2
  flutter_map_location_marker: ^5.0.0+1
  maps_launcher: ^2.0.1
  location_picker_flutter_map: ^1.1.5
  #maps: ^0.5.0
  #google_map_location_picker: ^4.1.7

  #服务
  flutter_local_notifications: ^13.0.0 #本地通知，不支持windows和web
  #onesignal_flutter: ^3.5.0 #要求OneSignal Account
  intercom_flutter: ^7.6.3+1
  #pusher_channels_flutter: ^2.0.1
  flutter_apns: ^1.6.0
  mobpush_plugin: ^1.2.4 #有容量限制，收费
  xiao_mi_push_plugin: ^2.0.0
  huawei_push: ^6.7.0+300
  # 支持本地和fcm
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1
  #openai_gpt3_api:
  dart_openai: ^1.8.0
  chat_gpt_sdk: ^2.0.4
  flutter_chatgpt_api: ^1.1.0
  masamune_ai_openai: ^1.1.4
  whisper_dart: ^0.0.11
  openai_dalle_wrapper: ^1.0.0
  dart_chatgpt: ^1.0.2
dependency_overrides:
  photo_view: ^0.14.0
  device_info_plus: ^8.0.0
  ffi: ^2.0.1
  flutter_ion: ^1.0.0
  flutter_webrtc: ^0.9.19
  i18n_extension: ^6.0.0
  analyzer: ^5.2.0
  provider: ^6.0.1
  geolocator: ^9.0.2
  apple_maps_flutter: ^1.2.0
  webview_flutter: ^4.0.6
  #webview_flutter_android: ^3.1.1
  #webview_flutter_wkwebview: ^3.0.1
  #webview_flutter_web: ^0.1.0+4
  #webview_flutter_platform_interface: ^2.0.0
  webview_win_floating: 2.0.0 #webView for
    #git: https://github.com/jakky1/webview_win_floating.git
  sprintf: ^7.0.0
  flex_color_picker: ^3.0.0
  permission_handler: ^10.2.0
  file_picker: ^5.2.5
  intl: ^0.18.0
  image: ^4.0.12
  google_fonts: ^4.0.1
  material_design_icons_flutter: ^6.0.7096
  camera: ^0.10.0+3 #调用相机
  image_cropper: ^3.0.1
  full_picker: ^1.1.5
  collection: ^1.17.0
  firebase_messaging: ^14.2.1
  firebase_core: ^2.1.1
  video_player_platform_interface: ^6.0.1
  path: ^1.8.3
  dio: ^5.0.2 #^4.0.6 openai
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  analyzer: ^5.2.0
  build_runner: ^2.1.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
    - assets/wasm/sqlite3.wasm
    - assets/locale/
    - assets/icons/
    - assets/images/
    - assets/images/bg/
    - assets/images/emoji/
    - assets/medias/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
