name: colla_chat
description: A CollaChat Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 获取系统信息和操作
  flutter_background: ^1.1.0
  device_info: ^2.0.3
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3 #选取图库
  url_launcher: ^6.1.2 #打开系统浏览器
  package_info: ^2.0.2 #获取包信息
  open_file: ^3.2.1 #打开文件
  camera: ^0.9.8+1 #调用相机
  orientation: ^1.2.0 # 控制屏幕旋转
  geolocator: ^8.2.1
  package_info_plus: ^1.4.2
  device_info_plus: ^4.0.0
  network_info_plus: ^2.1.3
  beamer: ^1.4.1+1
  sensors_plus: ^1.3.1
  battery_plus: ^2.1.3
  flutter_contacts: ^1.1.4
  #contacts_service: ^0.4.6
  # 存储
  shared_preferences: ^2.0.10
  flutter_secure_storage: ^5.0.2
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.1
  sqlite3: ^1.7.1
  sqlite3_flutter_libs: ^0.5.7
  idb_shim: ^2.0.1
  idb_sqflite: ^1.1.0
  #floor: ^1.2.0
  # 网络功能
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  web_socket_channel: ^2.2.0
  cached_network_image: ^3.0.0
  connectivity: ^3.0.6 #网络连接
  connectivity_plus: ^2.3.0
  flutter_web_auth: ^0.4.0
  enough_mail: ^2.1.0
  enough_media: ^2.2.0
  enough_mail_html: ^2.0.0
  enough_mail_flutter: ^2.0.0
  xml: ^6.0.1
  telephony: 0.2.0
  # 加密安全
  cryptography: ^2.0.5 #ecc,aes
  cryptography_flutter: ^2.0.2
  bs58: ^1.0.2
  webcrypto: ^0.5.2
  pinenacl: ^0.3.4
  encrypt: ^5.0.1 #aes
  openpgp: ^3.2.8 #rsa,sha
  libsignal_protocol_dart: ^0.5.6
  crypto: ^3.0.1 #sha
  archive: any
  uuid: 3.0.6
  local_auth: any
  #standard_message_codec: any
  # 辅助开发工具
  pdfx: <2.0.1+3
  json_annotation: ^4.3.0
  permission_handler: ^10.0.0 #权限处理1
  provider: ^6.0.1 #状态管理
  flutter_local_notifications: ^9.5.3+1
  share_plus: ^4.0.4
  date_format: ^2.0.6
  classic_logger: any
  #flutter_easylogger: any
  country_pickers: ^2.0.0
  country_picker: ^2.0.15
  #international_phone_input: ^1.0.4
  phone_numbers_parser: any
  font_awesome_flutter: ^10.1.0
  onesignal_flutter: ^3.3.1
  flushbar: ^1.10.4
  #share: ^0.6.5
  flutter_emoji: ^2.2.1+1
  emoji_picker_flutter: ^1.3.1
  animated_bottom_navigation_bar: ^0.3.2
  fluro: ^2.0.3
  flutter_multi_formatter: ^2.5.1
  flutter_awesome_select: ^6.3.0
  phone_number: ^0.12.0+2
  #sim_info: ^0.1.3
  phone_form_field: ^6.1.0
  #flutter-international-phone-input:
  intl_phone_field: ^3.1.0
  mobile_number: ^1.0.4
  # 界面样式和组件
  badges: ^2.0.3
  extended_list: any
  glassmorphism: ^3.0.0
  #flui: 0.9.2
  syncfusion_flutter_datagrid: ^20.2.36
  pluto_grid: ^4.0.1
  data_table_2: any
  #file_saver: ^0.1.0
  #pluto_grid_export: ^1.0.2
  flutter_neumorphic: ^3.2.0
  fl_chart: ^0.50.5
  toast: ^0.3.0 #toast提示框
  extended_text: ^9.1.0 #文本扩展显示
  extended_text_field: ^10.1.0 #文字表情混入
  extended_text_library: ^9.1.0 #Flutter2.5用这个,,其他可注释
  azlistview: ^2.0.0 #特殊列表滑动
  webview_flutter: ^3.0.4 #web显示
  # flutter_echarts: ^2.3.0
  fluent_ui: ^3.12.0
  macos_ui: ^1.4.1
  flutter_material_color_picker: ^1.1.0+2
  animated_text_kit: ^4.2.1
  after_layout: ^1.1.0
  snapping_sheet: ^3.1.0
  google_fonts: ^3.0.1
  material_design_icons_flutter: ^5.0.6295
  #flutter_bloc: ^6.1.0
  #flutter_swiper: 1.1.6 # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_screenutil: ^5.5.3 # Flutter 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil
  # webrtc
  flutter_webrtc: ^0.8.7
  dart_webrtc: ^1.0.5
  livekit_client: ^1.0.0
  flex_color_picker: ^2.4.0
  # 多媒体
  #flutter_audio_waveforms: any
  photo_view: ^0.14.0 #图片显示
  flutter_sound: ^9.2.12 #音频处理
  audioplayers: ^1.0.1 #音频处理
  video_player: ^2.1.1 #视频播放
  flick_video_player: any
  flutter_image_compress: ^1.1.0 #图片压缩1
  video_thumbnail: ^0.5.2
  syncfusion_flutter_barcodes: any
  qr_flutter: ^4.0.0
  #barcode_widget: ^2.0.2
  barcode_scan2: ^4.2.1
  mobile_scanner: ^2.0.0
  image_gallery_saver: ^1.7.1
  extended_image: ^6.0.1
  extended_image_library: ^3.3.0
  cross_file: any
  filesystem_picker: ^2.0.1
  file_picker: ^4.6.0
  flutter_quill: ^5.0.3
  #visual_editor: any
  universal_html: ^2.0.8
  #本地化
  lpinyin: ^2.0.3 #拼音
  wechat_assets_picker: ^7.3.2 #微信图库
  intl: ^0.17.0
  #intl_translation: any
  #intl_translation_format: any
  flutter_localizations:
    sdk: flutter
  # 参考学习
  #stream_chat_flutter: ^4.0.0
  #stream_chat_flutter_core: ^4.1.0
  #stream_chat: ^4.1.0
  #stream_chat_persistence: ^4.1.0
  #stream_chat_localizations: ^3.1.0
dependency_overrides:
  photo_view: ^0.14.0
  device_info_plus: ^4.0.0
  #qr: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  #analyzer: ^4.1.0
  #floor_generator: ^1.2.0
  build_runner: ^2.1.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
    - assets/wasm/sqlite3.wasm
    - assets/locale/
    - assets/icons/
    - assets/images/
    - assets/images/bg/
    - assets/images/emoji/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages