name: colla_chat
description: A Collaboration Chat Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # 系统功能，获取系统信息和操作，需要调用插件才能完成
  flutter_background: ^1.2.0
  flutter_background_service: ^3.0.1
  flutter_background_executor: ^1.0.0
  path_provider: ^2.0.11
  url_launcher: ^6.1.11 #打开系统浏览器
  open_file: ^3.2.1 #打开文件, 和最新device_info有版本冲突
  camera_windows: ^0.2.1+2
  camera_web: ^0.3.1+3
  wechat_camera_picker: ^3.8.0 #移动平台，wechat_assets_picker的扩展，照相，录像
  photo_manager: ^2.6.0 #移动平台，图像等媒体的抽象，wechat_assets_picker使用
  screenshot: ^2.1.0
  orientation: ^1.2.0 # 控制屏幕旋转
  geolocator: ^9.0.2
  device_info_plus: ^8.0.0
  network_info_plus: ^4.0.1
  beamer: ^1.4.1+1
  sensors_plus: ^3.0.2
  battery_plus: 4.0.1
  package_info_plus: 4.0.2
  flutter_contacts: ^1.1.6
  fluttercontactpicker: ^4.7.0
  #fast_contacts: ^3.0.3
  connectivity_plus: ^4.0.1
  #flutter_nearby_connections: ^1.1.1  #ANDROID，IOS，目前不支持ios和android之间通信，而且gradle版本配置低，需要修改
  nearby_connections: ^4.0.0 #android
  nfc_manager: ^3.3.0 #mobile
  flutter_nfc_kit: ^3.3.1 #mobile
  #  flutter_blue_plus: ^1.5.2 #ANDROID，IOS，MACOS
  mimecon: ^0.0.2
  wakelock: ^0.6.2 #让系统不会睡眠

  # 存储
  shared_preferences: ^2.0.10
  flutter_secure_storage: ^8.0.0
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.13
  idb_shim: ^2.0.1

  #网络
  dart_webrtc: ^1.0.16
  dio: ^5.0.2
  dio_http2_adapter: ^2.1.0
  web_socket_channel: ^2.2.0
  #cached_network_image: ^3.0.0
  #flutter_sms: ^2.3.3 #android compile failure
  #sms_advanced: ^1.0.2 #android版本有问题
  #flutter_sms_plus: ^1.0.1 #不支持ios
  #telephony: ^0.2.0
  telephony: #不再维护了
    git:
      url: https://github.com/suhardik/s_telephony.git
      ref: develop
  openvpn_flutter: ^1.2.2
  flutter_web_auth_2: ^2.1.5

  #界面
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  simple_icons: ^7.10.0 #icon: Icon(SimpleIcons.github)
  fluttericon: ^2.0.0
  flutter_animated_icons: ^1.0.0
  country_pickers: ^2.0.0
  country_picker: ^2.0.15
  font_awesome_flutter: ^10.1.0
  #flushbar: ^1.10.4
  #share: ^0.6.5
  flutter_emoji: ^2.4.0
  emoji_picker_flutter: ^1.5.2
  fluro: ^2.0.3
  flutter_multi_formatter: ^2.5.1
  #flutter_awesome_select: ^6.5.0
  #awesome_select: ^6.0.0
  #multi_select_flutter: ^4.1.2
  chips_choice: ^3.0.0
  #fancy_password_field: ^2.0.0
  flutter_pw_validator: ^1.6.0 #FlutterPwValidator放在TextFormField下面显示校验结果
  fzregex: ^2.0.0 #静态方法：Fzregex.hasMatch
  phone_number: ^2.0.1 #仅支持ios和android，解析电话号码
  #sim_info: ^0.1.3
  phone_form_field: ^8.1.0 #支持所有平台，电话号码的录入字段
  #flutter-international-phone-input:
  intl_phone_field: ^3.2.0 #支持所有平台，电话号码的录入字段
  mobile_number: ^2.1.1 #仅支持android，获取电话号码，ios无此功能
  phone_numbers_parser: ^8.0.0 #支持所有的平台
  badges: ^3.0.2
  extended_list: any
  glassmorphism: ^3.0.0
  glass_kit: ^2.0.1
  #flui: 0.9.2
  pluto_grid: ^7.0.2
  data_table_2: any
  file_saver: ^0.2.5
  #pluto_grid_export: ^1.0.2
  #flutter_neumorphic: ^3.2.0
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  fl_chart: ^0.61.0
  fluttertoast: ^8.2.1
  extended_text: ^11.0.0 #文本扩展显示
  extended_text_field: ^12.0.0 #文字表情混入
  extended_text_library: ^11.0.0 #Flutter2.5用这个,,其他可注释
  azlistview: ^2.0.0 #特殊列表滑动
  graphic: ^2.0.2
  flutter_echarts: ^2.4.0
  fluent_ui: 4.6.1
  fluentui_system_icons: ^1.1.201 #FluentIcons.access_time_24_regular
  macos_ui: ^1.11.1
  flutter_material_color_picker: ^1.1.0+2
  after_layout: ^1.1.0
  snapping_sheet: ^3.1.0 #在上下可以滑出的sheet

  #flutter_bloc: ^6.1.0
  flutter_screenutil: ^5.5.3 # Flutter 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil
  easy_stepper: ^0.7.2
  flex_color_scheme: ^7.1.2
  flex_seed_scheme: ^1.3.0
  file_selector: ^1.0.0
  filesystem_picker: ^3.1.0
  wechat_assets_picker: ^8.4.0 #移动平台，选择图像，视频等媒体并展示
  flutter_slidable: ^3.0.0 #滑动的按钮
  #下面是各种轮播图组件
  carousel_slider: ^4.2.1 #不错的类似swiper的组件
  flutter_carousel_widget: ^2.0.4 #类似carousel_slider
  card_swiper: ^3.0.1 #不错的swiper的组件
  flutter_card_swiper: ^6.0.0 #不错的swiper的组件
  another_transformer_page_view: ^2.0.1
  appinio_swiper: ^2.0.2 #不错的swiper的组件，可定制动画的角度
  flutter_drawing_board: ^0.4.4+2 #绘画工具
  custom_pop_up_menu: ^1.2.4
  #popup_menu: ^1.0.5
  star_menu: ^3.1.0+1
  flutter_floating_bottom_bar: ^1.1.0
  focused_menu: ^1.0.5
  floating_action_bubble: ^1.1.4
  expandable: ^5.0.1
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.1
  responsive_sizer: ^3.1.1

  #界面效果动画
  flutter_adaptive_scaffold: ^0.1.5
  simple_animations: ^5.0.2
  flutter_animate: ^4.2.0
  auto_animated: ^3.1.0 #对滚动视图内的元素定义动画
  animations: ^2.0.7
  animate_do: ^3.0.2
  animated_text_kit: ^4.2.1
  loading_indicator: ^3.1.1
  loading_animation_widget: ^1.2.0+4

  #安全加密
  cryptography: ^2.0.5 #ecc,aes
  #在macos上不能使用，error: cannot call value of non-function type 'FlutterBinaryMessenger'
  #cryptography_flutter: ^2.0.2
  bs58: ^1.0.2
  webcrypto: ^0.5.3
  pinenacl: ^0.5.1
  encrypt: ^5.0.1 #aes
  openpgp: ^3.2.8 #rsa,sha
  libsignal_protocol_dart: ^0.7.1
  crypto: ^3.0.1 #sha
  archive: ^3.3.7
  uuid: 3.0.7
  local_auth: any
  #基本开发工具
  xml: ^6.0.1
  mime: ^1.0.2
  flutter_keyboard_visibility: ^5.4.0
  keyboard_actions: ^4.2.0
  synchronized: ^3.0.0+2
  flutter_smart_dialog: ^4.9.2
  #pdf_flutter: ^1.1.4
  #syncfusion_flutter_pdfviewer: ^20.3.49
  syncfusion_flutter_datagrid: ^22.1.36
  json_annotation: ^4.3.0
  permission_handler: ^10.0.0 #权限处理1
  provider: ^6.0.1 #状态管理
  easy_refresh: ^3.3.2+1
  percent_indicator: ^4.2.3
  share_plus: 7.0.2
  flutter_sharing_intent: ^1.0.6
  #  receive_sharing_intent: #^1.4.6 #gradle版本低的问题
  #    git:
  #      url: https://github.com/AyushmanG26/receive_sharing_intent.git
  date_format: ^2.0.6
  omni_datetime_picker: ^1.0.1
  toggle_switch: ^2.0.1
  classic_logger: any
  logger: ^1.1.0
  #logging: ^1.0.2
  cross_file: 0.3.3+4
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  qr: ^3.0.1
  #barcode: ^2.2.3
  #barcode_image: ^2.0.2
  #barcode_widget: ^2.0.2
  barcode_scan2: ^4.2.4
  #mobile_scanner: ^2.0.0  #macos有问题
  lpinyin: ^2.0.3 #拼音
  window_manager: ^0.3.4 #桌面应用的窗口管理
  #有特殊安装要求，否则编译出错
  #webview_windows: ^0.2.2
  #flutter_inappwebview: ^5.7.2+3
  #flutter_webview_pro: ^3.0.1+4
  #easy_web_view: ^1.6.0
  flutter_widget_from_html: ^0.13.0-alpha.1

  any_link_preview: ^3.0.1 #预览link

  # 多媒体
  #flutter_audio_waveforms: any
  photo_view: ^0.14.0 #图片显示
  #音频处理 ios:Just add those 2 flags in XCode > Build Settings > Other Linker Flags :
  #-lc++
  #-lstd++
  flutter_sound: ^9.2.13
  audioplayers: ^4.1.0 #音频处理,所有平台
  audioplayers_platform_interface: ^5.0.1
  audioplayers_windows: ^2.0.2
  audioplayers_darwin: ^4.1.0
  audioplayers_linux: ^2.1.0
  audioplayers_web: ^3.1.0
  audioplayers_android: ^3.0.2
  another_audio_recorder: ^1.0.1
  assets_audio_player: ^3.0.6
  audiofileplayer: ^2.1.1
  record_mp3: ^3.0.0
  audio_waveforms: 1.0.4
  video_player_web: ^2.0.15
  flick_video_player: ^0.5.0 #video_player的封装
  #appinio_video_player: ^1.2.0 #video_player的封装
  video_player: ^2.6.0 #mobile and web
  video_player_win: ^2.2.0
  video_player_macos: ^2.0.1
  video_player_control_panel: ^1.1.0
  chewie: ^1.3.6 #video_player的封装
  flutter_meedu_videoplayer: ^4.2.11-dev-5
  media_kit: ^1.0.2                             # Primary package.
  media_kit_video: ^1.0.2                       # For video rendering.
  media_kit_native_event_loop: ^1.0.4            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_android_video: ^1.0.6           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2
  #better_player: ^0.0.83 #chewie的封装,ios下有问题
  #fijkplayer: ^0.10.1 #mobile
  just_audio: ^0.9.30
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.4
  just_waveform: ^0.0.4
  audio_service: ^0.18.9
  just_audio_background: ^0.0.1-beta.9
  audio_session: ^0.1.13
  flutter_tts: ^3.5.3
  speech_to_text: any
  flutter_image_compress: ^2.0.3
  video_thumbnail: ^0.5.2
  video_compress: ^3.1.2
  #thumbnailer: ^2.2.0
  fc_native_video_thumbnail: ^0.4.0
  image_gallery_saver: #^1.7.1
    git: https://github.com/hui-z/image_gallery_saver.git
  extended_image: ^8.0.2 #所有平台，官方软件，管理图像
  extended_image_library: ^3.4.2
  image_editor: ^1.3.0
  image: ^4.0.17 #所有平台，装载，保存，管理图像
  flutter_luban: ^0.1.13
  #image_cropping: ^0.0.13 #裁剪图片
  crop_your_image: ^0.7.4
  #chatview: ^1.2.1

  #应用
  #  flutter_filereader: 3.0.0 #引入x5浏览器
  i18n_extension: ^9.0.2
  quill_html_editor: ^2.1.9
  html_editor_enhanced: ^2.5.1
  flutter_quill: ^7.2.6
  vsc_quill_delta_to_html: ^1.0.3
  #git: https://github.com/singerdmx/flutter-quill.git
  flutter_quill_extensions: #^0.3.2
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      path: flutter_quill_extensions
  #  visual_editor:
  #    git: https://github.com/visual-space/visual-editor.git
  #youtube_player_flutter_quill: ^8.2.2
  flutter_rte: ^1.0.0
  appflowy_editor: ^1.0.3
  flutter_platform_widgets: ^3.3.5
  universal_html: ^2.0.8
  backdrop: ^0.9.0 #Use BackdropScaffold instead of the standard Scaffold in your app
  material_floating_search_bar: ^0.3.7
  google_maps_flutter: ^2.2.1
  #google_map_location_picker: ^4.1.7
  map_launcher: ^2.4.0 #Map Launcher is a flutter plugin to find available maps installed on a device and launch them
  flutter_svg: ^2.0.3
  apple_maps_flutter: ^1.2.0
  platform_maps_flutter: ^1.0.2
  maps_launcher: ^2.0.1
  location_picker_flutter_map: ^1.2.0
  #maps: ^0.5.0
  #google_map_location_picker: ^4.1.7

  #服务
  flutter_local_notifications: ^15.1.0+1 #本地通知，不支持windows和web
  #onesignal_flutter: ^3.5.0 #要求OneSignal Account
  intercom_flutter: ^7.6.3+1
  #pusher_channels_flutter: ^2.0.1
  flutter_apns: ^1.6.0
  #xiao_mi_push_plugin: ^2.0.0  #android下有错误，gradle的配置旧了
  huawei_push: ^6.7.0+300
  # 支持本地和fcm
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1 #对minsdk有要求
  flutter_native_splash: ^2.2.19
  system_tray: ^2.0.2
  tray_manager: ^0.2.0
  #openai_gpt3_api:
  dart_openai: ^3.0.0
  chat_gpt_sdk: ^2.0.4
  flutter_chatgpt_api: ^1.1.0
  masamune_ai_openai: ^2.1.3
  whisper_dart: ^0.0.11
  openai_dalle_wrapper: ^1.0.0
  dart_chatgpt: ^1.0.2
dependency_overrides:
  flutter_math_fork: ^0.7.1
  photo_view: ^0.14.0
  device_info_plus: ^9.0.2
  ffi: ^2.0.1
  flutter_ion: ^1.0.0
  flutter_webrtc: ^0.9.36
  analyzer: ^6.0.0
  provider: ^6.0.1
  geolocator: ^9.0.2
  apple_maps_flutter: ^1.2.0
  http: ^1.1.0
  flutter_inappwebview: ^6.0.0-beta.24+1
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.7.1
  webview_flutter_wkwebview: ^3.4.4
  webview_flutter_web: ^0.2.2+1
  webview_flutter_platform_interface: ^2.3.1
  webview_win_floating: #2.0.0 #webView for
    git: https://github.com/jakky1/webview_win_floating.git
  #  desktop_webview_window: ^0.2.0
  sprintf: ^7.0.0
  flex_color_picker: ^3.1.0
  permission_handler: ^10.2.0
  file_picker: ^5.3.2
  intl: ^0.18.0
  image: ^4.0.12
  google_fonts: ^5.1.0
  material_design_icons_flutter: ^7.0.7296
  camera: ^0.10.3+2 #调用相机
  image_cropper: ^5.0.0
  full_picker: ^1.3.3 #和最新版的record5不兼容,Recorder被AudioRecorder替换，需要修改源码
  collection: ^1.17.0
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  video_player_platform_interface: ^6.0.1
  path: ^1.8.3
  dio: ^5.0.2 #^4.0.6 openai
  audio_video_progress_bar: ^1.0.0
  pdfx: 2.2.0 #2.3.0在macos下编译错误,web下不能使用
  #printing: ^5.11.0 #所有平台，使用pdf，把一些其他的格式转换成pdf并显示，目前windows下有bug
  #  printing:
  #    git:
  #      url: https://github.com/DavBfr/dart_pdf
  #      ref: master
  #      path: printing
  pdf: ^3.10.4 #所有平台，创建pdf
  record: ^5.0.0-beta.2
  visibility_detector: ^0.4.0+2 #组建可见性的大小发生变化
  focus_detector: ^2.0.1 #组建在界面上消失或者出现
  image_picker: ^1.0.0 #选取图库,移动从图像廊或者相机选，桌面实现采用file_selector，从文件系统选
  latlong2: ^0.9.0
  flutter_map_location_marker: ^7.0.0
  flutter_map: ^5.0.0
  win32: ^4.1.4
  markdown: ^6.0.1
  lottie: ^2.4.0
  enough_mail:
    git: https://github.com/Enough-Software/enough_mail.git
  enough_media: #^2.2.0
    git: https://github.com/enough-software/enough_media
  enough_mail_html: #^2.0.0
    git: https://github.com/Enough-Software/enough_mail_html.git
  enough_html_editor: #^0.0.5
    git: https://github.com/Enough-Software/enough_html_editor.git
  enough_platform_widgets: #^0.7.2
    git: https://github.com/Enough-Software/enough_platform_widgets
  enough_mail_flutter: #^2.0.0 #ios崩溃
    git: https://github.com/Enough-Software/enough_mail_flutter.git
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  analyzer: ^6.0.0
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/images/app1024.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/app1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app1024.png"
flutter_native_splash:
  background_image: "assets/images/splash_bg.png"
  image: assets/images/splash.png
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
    - assets/wasm/sqlite3.wasm
    - assets/locale/
    - assets/icons/
    - assets/images/
    - assets/images/bg/
    - assets/images/emoji/
    - assets/images/email/
    - assets/medias/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
