name: colla_chat
description: colla_chat Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 系统功能，获取系统信息和操作，需要调用插件才能完成
  flutter_background: ^1.1.0
  flutter_background_service: ^2.4.5
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3 #选取图库
  url_launcher: ^6.1.6 #打开系统浏览器
  package_info: ^2.0.2 #获取包信息
  open_file: ^3.2.1 #打开文件, 和最新device_info有版本冲突
  camera: ^0.10.0+3 #调用相机
  camera_windows: ^0.2.1+2
  camera_web: ^0.3.0+1
  wechat_camera_picker: ^3.6.1
  photo_manager: ^2.5.0
  screenshot: ^1.2.3
  images_picker: ^1.2.11
  orientation: ^1.2.0 # 控制屏幕旋转
  geolocator: ^9.0.2
  package_info_plus: ^1.4.2
  device_info_plus: ^4.1.2
  network_info_plus: ^2.1.3
  beamer: ^1.4.1+1
  sensors_plus: ^1.3.1
  battery_plus: ^2.1.3
  flutter_contacts: ^1.1.4
  connectivity_plus: ^3.0.0
  flutter_nearby_connections: ^1.1.1
  mimecon: ^0.0.2

  # 存储
  shared_preferences: ^2.0.10
  flutter_secure_storage: ^5.0.2
  sqlite3: ^1.7.1
  sqlite3_flutter_libs: ^0.5.7
  idb_shim: ^2.0.1

  #网络
  flutter_webrtc: ^0.9.16
  dart_webrtc: ^1.0.5
  #flutter_web_auth: ^0.4.0  #macos有问题
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  web_socket_channel: ^2.2.0
  cached_network_image: ^3.0.0
  telephony: 0.2.0

  #界面
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2
  country_pickers: ^2.0.0
  country_picker: ^2.0.15
  #international_phone_input: ^1.0.4
  phone_numbers_parser: any
  font_awesome_flutter: ^10.1.0
  onesignal_flutter: ^3.3.1
  flushbar: ^1.10.4
  #share: ^0.6.5
  flutter_emoji: ^2.2.1+1
  emoji_picker_flutter: ^1.3.1
  animated_bottom_navigation_bar: ^0.3.2
  flutter_animate: ^1.0.0
  fluro: ^2.0.3
  flutter_multi_formatter: ^2.5.1
  flutter_awesome_select: ^6.5.0
  phone_number: ^0.12.0+2
  #sim_info: ^0.1.3
  phone_form_field: ^6.1.0
  #flutter-international-phone-input:
  intl_phone_field: ^3.1.0
  mobile_number: ^1.0.4
  badges: ^2.0.3
  extended_list: any
  glassmorphism: ^3.0.0
  glass_kit: ^2.0.1
  #flui: 0.9.2
  syncfusion_flutter_datagrid: ^20.2.36
  pluto_grid: ^4.0.1
  data_table_2: any
  file_saver: ^0.1.0
  #pluto_grid_export: ^1.0.2
  flutter_neumorphic: ^3.2.0
  fl_chart: ^0.50.5
  toast: ^0.3.0 #toast提示框
  extended_text: ^9.1.2 #文本扩展显示
  extended_text_field: ^10.2.0 #文字表情混入
  extended_text_library: ^9.1.0 #Flutter2.5用这个,,其他可注释
  azlistview: ^2.0.0 #特殊列表滑动
  # flutter_echarts: ^2.3.0
  fluent_ui: ^3.12.0
  macos_ui: ^1.4.1
  flutter_material_color_picker: ^1.1.0+2
  animated_text_kit: ^4.2.1
  after_layout: ^1.1.0
  snapping_sheet: ^3.1.0
  google_fonts: ^3.0.1
  material_design_icons_flutter: ^5.0.6295
  #flutter_bloc: ^6.1.0
  #flutter_swiper: 1.1.6 # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper_null_safety: any
  flutter_screenutil: ^5.5.3 # Flutter 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil
  flex_color_picker: ^2.4.0
  file_picker: ^5.2.2
  filesystem_picker: ^3.1.0
  wechat_assets_picker: ^8.0.2 #微信图库
  full_picker: ^1.1.5
  flutter_slidable: ^2.0.0
  flutter_drawing_board: ^0.3.1

  #安全加密
  cryptography: ^2.0.5 #ecc,aes
  #在macos上不能使用，error: cannot call value of non-function type 'FlutterBinaryMessenger'
  #cryptography_flutter: ^2.0.2
  bs58: ^1.0.2
  webcrypto: ^0.5.3
  pinenacl: ^0.3.4
  encrypt: ^5.0.1 #aes
  openpgp: ^3.2.8 #rsa,sha
  libsignal_protocol_dart: ^0.5.6
  crypto: ^3.0.1 #sha
  archive: any
  uuid: 3.0.6
  local_auth: any

  #基本开发工具
  xml: ^6.0.1
  mime: ^1.0.2
  flutter_keyboard_visibility: ^5.4.0
  keyboard_actions: ^4.1.0
  synchronized: ^3.0.0+2
  flutter_smart_dialog: ^4.7.1
  pdfx: ^2.3.0
  #pdf_flutter: ^1.1.4
  pdf: ^3.8.3
  #syncfusion_flutter_pdfviewer: ^20.3.49
  json_annotation: ^4.3.0
  permission_handler: ^10.0.0 #权限处理1
  provider: ^6.0.1 #状态管理
  flutter_local_notifications: ^9.5.3+1
  pull_to_refresh_notification: ^2.3.0
  share_plus: ^4.0.4
  receive_sharing_intent: ^1.4.5
  date_format: ^2.0.6
  classic_logger: any
  logger: ^1.1.0
  #logging: ^1.0.2
  cross_file: any
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  qr: ^3.0.1
  #barcode: ^2.2.3
  #barcode_image: ^2.0.2
  #barcode_widget: ^2.0.2
  barcode_scan2: ^4.2.1
  #mobile_scanner: ^2.0.0  #macos有问题
  lpinyin: ^2.0.3 #拼音
  intl: ^0.17.0
  window_manager: any
  #有特殊安装要求，否则编译出错
  #webview_windows: ^0.2.2
  flutter_inappwebview: ^6.0.0-beta.12
  #flutter_webview_pro: ^3.0.1+4
  webview_flutter: ^3.0.4 #web显示

  # 多媒体
  #flutter_audio_waveforms: any
  photo_view: ^0.14.0 #图片显示
  #音频处理 ios:Just add those 2 flags in XCode > Build Settings > Other Linker Flags :
  #-lc++
  #-lstd++
  flutter_sound: ^9.2.13
  audio_session: ^0.1.6
  audioplayers: ^1.0.1 #音频处理
  another_audio_recorder: ^1.0.1
  record_mp3: ^3.0.0
  audio_waveforms: ^0.1.5
  video_player_web: ^2.0.12
  flick_video_player: ^0.5.0
  video_player: ^2.4.7
  dart_vlc: ^0.2.1
  chewie: ^1.3.5
  fijkplayer: ^0.10.1
  flutter_vlc_player: ^7.1.5
  record: ^4.4.0
  just_audio: ^0.9.25
  just_audio_windows: ^0.1.0
  just_audio_mpv: ^0.1.4
  just_waveform: any
  audio_service: any
  just_audio_background: ^0.0.1-beta.7
  flutter_tts: ^3.5.3
  speech_to_text: any
  flutter_image_compress: ^1.0.0-nullsafety #图片压缩1
  video_thumbnail: ^0.5.2
  image_gallery_saver: ^1.7.1
  extended_image: ^6.3.2
  extended_image_library: ^3.4.1
  image_editor: ^1.3.0
  image: ^3.2.0
  flutter_luban: ^0.1.13
  image_cropping: ^0.0.13

  #应用
  flutter_filereader: 3.0.0
  i18n_extension: ^5.0.1
  flutter_quill: ^6.1.2
  visual_editor:
    git: https://github.com/visual-space/visual-editor.git
  universal_html: ^2.0.8
  enough_mail: ^2.1.0
  enough_media: ^2.2.0
  enough_mail_html: ^2.0.0
  #在ios下会引发启动崩溃
  #enough_mail_flutter: ^2.0.0 #ios崩溃
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  backdrop: ^0.8.1 #Use BackdropScaffold instead of the standard Scaffold in your app
  sliding_up_panel: ^2.0.0+1
  material_floating_search_bar: ^0.3.7
  google_maps_flutter: ^2.2.1
  #google_map_location_picker: ^4.1.7
  map_launcher: ^2.4.0 #Map Launcher is a flutter plugin to find available maps installed on a device and launch them
  flutter_svg: any
  apple_maps_flutter: ^1.2.0
  platform_maps_flutter: ^1.0.2
  flutter_map_location_marker: ^5.0.0+1
  maps_launcher: ^2.0.1
dependency_overrides:
  photo_view: ^0.14.0
  device_info_plus: ^4.1.2
  ffi: ^2.0.1
  flutter_ion: ^1.0.0
  flutter_webrtc: ^0.9.16
  i18n_extension: ^5.0.1
  youtube_player_flutter: ^8.1.1
  flutter_inappwebview: ^6.0.0-beta.12
  provider: ^6.0.1
  geolocator: ^9.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  analyzer: ^4.1.0
  build_runner: ^2.1.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
    - assets/wasm/sqlite3.wasm
    - assets/locale/
    - assets/icons/
    - assets/images/
    - assets/images/bg/
    - assets/images/emoji/
    - assets/medias/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
