name: colla_chat
description: A Collaboration Chat Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.6.1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # 尝试使用的功能
  get: ^5.0.0-release-candidate-6
  bonsoir: ^5.1.9
  process_runner: ^4.2.0
  network_tools: ^5.0.2
  network_tools_flutter: ^2.0.2
  # 系统功能，获取系统信息和操作，需要调用插件才能完成
  flutter_background: ^1.3.0+1  #android,后台运行，可以保持网络连接
  flutter_foreground_service: ^0.4.1 #android,后台运行，可以保持网络连接，和flutter_background功能一样
  flutter_foreground_task: ^8.8.1+1
  flutter_background_service: ^5.0.10
  flutter_background_executor: ^1.0.0
  system_alert_window: ^2.0.0
  flutter_overlay_window: ^0.4.3
  flutter_floating: ^1.0.8
  upgrader: ^11.0.0
  path_provider: ^2.0.11
  url_launcher: ^6.1.11 #打开系统浏览器
  open_filex: ^4.4.0 #打开文件,
  camera_windows: ^0.2.1+9
  camera_linux: ^0.0.8
  camera_web: ^0.3.1+4
  camera_macos: ^0.0.8
  wechat_camera_picker: ^4.3.2 #移动平台，wechat_assets_picker的扩展，照相，录像
  photo_manager: ^3.3.0 #移动平台，图像等媒体的抽象，wechat_assets_picker使用
  screenshot: ^3.0.0
  no_screenshot: 0.2.0 #^0.3.1
  screenshot_callback: ^3.0.1
  orientation: ^1.2.0 # 控制屏幕旋转
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  device_info_plus: ^9.1.2
  network_info_plus: ^6.0.0
  beamer: ^1.4.1+1
  battery_plus: ^6.0.0
  flutter_contacts: ^1.1.8
  fluttercontactpicker: ^5.0.0
  nearby_connections: ^4.0.0 #android
  nfc_manager: ^3.4.0 #mobile
  flutter_nfc_kit: ^3.4.2 #mobile
  mimecon: ^1.0.1
  wakelock_plus: ^1.2.5 #让系统不会睡眠

  # 存储
  flutter_secure_storage: 9.2.2
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.23
  idb_shim: ^2.0.1

  #网络
  dio: ^5.7.0
  dio_http2_adapter: ^2.1.0
  telephony: #不再维护了
    git:
      url: https://github.com/suhardik/s_telephony.git
      ref: develop
  openvpn_flutter: ^1.3.0
  flutter_web_auth_2: ^3.0.3

  #界面
  bubble: ^1.2.1
  fluttertoast: ^8.2.1
  flutter_local_notifications: ^17.1.2
  alarm: ^3.1.2
  stacked_notification_cards: ^0.1.0-dev.5
  toastification: ^2.0.0
  cupertino_icons: ^1.0.8 #CupertinoIcons.heart_fill
  # Icon(AntDesign.gitlab_fill),Icon(Bootstrap.google),Icon(BoxIcons.bxl_apple),Brand(Brands.icons8)
  # Icon(Clarity.map_outline_badged),Icon(EvaIcons.clipboard),Flag(Flags.india),Icon(FontAwesome.stripe_brand)
  # Icon(HeroIcons.printer),Icon(Iconsax.cake_bold),Icon(IonIcons.bug),Icon(LineAwesome.amazon)
  # Icon(MingCute.knife_line),Icon(OctIcons.code_of_conduct),Icon(PixelArtIcons.gif),Icon(TeenyIcons.google_play_store)
  # Icon(ZondIcons.shield)
  icons_plus: ^5.0.0
  simple_icons: ^10.1.3 #icon: Icon(SimpleIcons.github)
  fluttericon: ^2.0.0 #Icon(Typicons.attention), Icon(Fontelico.emo_wink), Icon(Linecons.globe)
  unicons: ^3.0.0 #Icon(UniconsLine.camera),Icon(UniconsSolid.airplay)
  flutter_animated_icons: ^1.0.1
  flutter_material_design_icons: ^1.1.7447 #Icon(MdiIcons.abacus)
  hugeicons: ^0.0.7 #HugeIcons.strokeRoundedHome01
  country_pickers: ^3.0.1
  country_picker: ^2.0.15
  font_awesome_flutter: ^10.1.0
  unicode_emojis: ^0.4.0
  fluro: ^2.0.3
  flutter_multi_formatter: ^2.5.1
  chips_choice: ^3.0.0
  validation_pro: 1.2.0
  flutter_pw_validator: ^1.6.0 #FlutterPwValidator放在TextFormField下面显示校验结果
  fzregex: ^2.0.0 #静态方法：Fzregex.hasMatch
  regexpattern: ^2.5.0
  phone_number: ^2.0.1 #仅支持ios和android，解析电话号码
  phone_form_field: ^9.0.4 #支持所有平台，电话号码的录入字段
  intl_phone_field: ^3.2.0 #支持所有平台，电话号码的录入字段
  mobile_number: ^2.1.1 #仅支持android，获取电话号码，ios无此功能
  phone_numbers_parser: ^9.0.0 #支持所有的平台
  badges: ^3.1.2
  extended_list: ^3.0.0
  glass_kit: ^4.0.1
  #flui: 0.9.2
  pluto_grid: ^8.0.0
  data_table_2: ^2.5.8
  file_saver: ^0.2.10
  material_neumorphic: ^1.2.1
  clay_containers: ^0.3.4
  fl_chart: ^0.68.0
  k_chart: ^0.7.1
  community_charts_flutter: ^1.0.4
  extended_text: ^14.0.1 #文本扩展显示
  extended_text_field: ^16.0.0 #文字表情混入
  extended_text_library: ^12.0.0
  extended_masked_text: ^3.0.1
  azlistview: ^2.0.0 #特殊列表滑动
  graphic: ^2.5.0 # 各种图表，取代flutter_echarts
  flutter_unity_widget: ^2022.2.1
  flutter_embed_unity: ^1.2.3
  opencv_dart: ^1.2.5
  flame: ^1.21.0
  candlesticks:
    git:
      url: https://github.com/r-mzy47/candlesticks.git
  fluent_ui: 4.9.1
  fluentui_system_icons: ^1.1.201 #FluentIcons.access_time_24_regular
  macos_ui: ^2.0.9
  flutter_material_color_picker: ^1.2.0
  after_layout: ^1.1.0
  snapping_sheet: ^3.1.0 #在上下可以滑出的sheet
  device_preview: ^1.2.0
  flutter_screenutil: ^6.0.0-alpha.1 # Flutter 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil
  easy_stepper: ^0.8.1
  flex_color_scheme: ^7.3.1
  file_selector: ^1.0.3
  filesystem_picker: ^4.1.0
  wechat_assets_picker: ^9.2.1 #移动平台，选择图像，视频等媒体并展示
  flutter_slidable: ^3.0.1 #滑动的按钮
  #下面是各种轮播图组件
  carousel_slider: ^5.0.0 #不错的类似swiper的组件 CarouselSlider
  flutter_carousel_widget: ^3.0.1 #类似carousel_slider，支持单页多item
  card_swiper: ^3.0.1 #不错的swiper的组件
  flutter_card_swiper: ^7.0.0 #不错的swiper的组件
  another_transformer_page_view: ^2.0.1
  appinio_swiper: ^2.0.2 #不错的swiper的组件，可定制动画的角度
  flutter_drawing_board: ^0.9.4 #绘画工具
  custom_pop_up_menu: ^1.2.4
  star_menu: ^4.0.1
  sliding_up_panel2: ^3.3.0+1
  flutter_floating_bottom_bar: ^1.1.0
  focused_menu: ^1.0.5
  floating_action_bubble: ^1.1.4
  expandable: ^5.0.1
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.1
  responsive_sizer: ^3.1.1
  introduction_screen: ^3.1.14
  pinput: ^5.0.0
  align_positioned: ^4.0.1
  #  chart_sparkline: ^1.1.1
  super_drag_and_drop: ^0.8.22
  dashbook: ^0.1.15

  #界面效果动画
  flutter_adaptive_scaffold: ^0.2.1
  simple_animations: ^5.0.2
  flutter_animate: ^4.2.0
  auto_animated: ^3.1.0 #对滚动视图内的元素定义动画
  animations: ^2.0.11
  animate_do: ^3.0.2
  animated_text_kit: ^4.2.1
  loading_indicator: ^3.1.1
  loading_animation_widget: ^1.2.0+4
  mini_music_visualizer: ^1.1.4

  #安全加密
  cryptography: ^2.7.0 #ecc,aes
  cryptography_flutter: ^2.3.2
  pointycastle: ^3.7.4
  encrypt: ^5.0.3 #aes
  openpgp: ^3.8.2 #rsa,sha
  libsignal_protocol_dart: ^0.7.1
  crypto: ^3.0.3 #sha
  bs58: ^1.0.2
  archive: ^3.3.7
  local_auth: ^2.2.0

  #基本开发工具
  xml: ^6.0.1
  mime: ^1.0.2
  keyboard_actions: ^4.2.0
  synchronized: ^3.3.0+2
  flutter_smart_dialog: ^4.9.4
  json_annotation: ^4.3.0
  provider: ^6.0.1 #状态管理
  easy_refresh: ^3.3.2+1
  percent_indicator: ^4.2.3
  flutter_sharing_intent: 1.1.0
  date_format: ^2.0.6
  omni_datetime_picker: ^2.0.3
  toggle_switch: ^2.0.1
  talker: ^4.2.4
  talker_flutter: ^4.2.0
  cross_file: ^0.3.4+1
  mobile_scanner: ^5.2.3
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  qr: ^3.0.1
  lpinyin: ^2.0.3 #拼音
  window_manager: ^0.4.0 #桌面应用的窗口管理
  #有特殊安装要求，否则编译出错
  any_link_preview: ^3.0.1 #预览link

  # 多媒体
  ffmpeg_kit_flutter: ^6.0.3 #Android, iOS and macOS
  photo_view: ^0.14.0 #图片显示
  pro_image_editor: ^5.2.2
  flutter_sound: ^9.4.6
  audioplayers: ^6.0.0 #音频处理,所有平台
  audioplayers_platform_interface: ^7.0.0
  audioplayers_windows: ^4.0.0
  audioplayers_darwin: ^6.0.0
  audioplayers_linux: ^4.0.0
  audioplayers_web: ^5.0.0
  audioplayers_android: ^5.0.0
  audio_waveforms: 1.0.5
  video_player_web: ^2.3.1
  flick_video_player: ^0.9.0 #video_player的封装
  video_player: ^2.9.1 #mobile and web
  video_player_platform_interface: ^6.2.2
  video_player_win: ^2.3.9
  video_player_macos: ^2.0.1
  video_player_android: ^2.5.2
  video_player_control_panel: ^1.1.1
#  native_video_player: ^1.3.1
  #  fvp: ^0.19.0
  fl_video: ^1.4.0  #video_Player control panel
  chewie: ^1.3.6 #video_player的封装
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4
  video_player_media_kit: ^1.0.5
  just_audio: ^0.9.40
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.4
  just_waveform: ^0.0.4
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.18
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.2
  sherpa_onnx: ^1.10.14
  flutter_image_compress: ^2.3.0
  video_thumbnail: ^0.5.2
  video_compress: ^3.1.2
  fc_native_video_thumbnail: ^0.12.0
  extended_image: ^8.2.0 #所有平台，官方软件，管理图像
  extended_image_library: ^4.0.2
  image_editor: ^1.5.1
  image: ^4.0.17 #所有平台，装载，保存，管理图像
  flutter_luban: ^0.1.14
  dismissible_page: ^1.0.2
  infinite_scroll_pagination: ^4.0.0

  #应用
  i18n_extension: ^12.0.1
  quill_html_editor: ^2.2.8
  html_editor_enhanced: ^2.6.0
  vsc_quill_delta_to_html: ^1.0.5
  flutter_platform_widgets: 7.0.0
  universal_html: ^2.0.8
  backdrop: ^0.9.0 #Use BackdropScaffold instead of the standard Scaffold in your app
  material_floating_search_bar: ^0.3.7
  flutter_svg: ^2.0.3
  latlong2: ^0.9.0
  flutter_map_location_marker: 9.0.0
  flutter_map: ^7.0.2 #Open Street Map，需要翻墙
  apple_maps_flutter: ^1.3.0
  google_maps_flutter: ^2.6.1 #谷歌地图，移动设备
  tencent_map_flutter: ^0.1.0
  platform_maps_flutter: ^1.0.2 #融合谷歌地图和苹果地图
  map_launcher: ^3.3.1 #打开设备已安装的地图软件，移动设备
  location_picker_flutter_map: ^3.0.1 #Open Street Map，需要翻墙

  #服务
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  # 支持本地和fcm
  awesome_notifications: ^0.9.2
  # awesome_notifications_fcm: ^0.9.2 #要付钱
  pull_to_refresh_notification: ^3.1.0
  intercom_flutter: ^9.0.1
  flutter_native_splash: ^2.4.1
  system_tray: ^2.0.3
  tray_manager: ^0.2.0
  livekit_client: ^2.2.5 #livekit sfu server flutter client
  livekit_server_sdk: ^1.0.0
  langchain: ^0.7.1
  langchain_ollama: ^0.3.0
  langchain_openai: ^0.7.0
  langchain_google: ^0.6.1
  ollama_dart: ^0.2.0
  dart_openai: ^5.1.0

  #系统
  system_status: ^1.0.7
  system_resources: ^1.6.0
dependency_overrides:
  uuid: ^4.3.1
  meta: ^1.11.0
  pointer_interceptor: ^0.10.1
  js: ^0.7.1
  web: ^1.0.0
  logger: ^2.3.0
  web_socket_channel: ^3.0.0
  web_socket_client: ^0.1.2
  websocket_universal: ^1.2.5
  flutter_math_fork: ^0.7.1
  share_plus: ^10.0.2
  sensors_plus: ^6.0.1
  photo_view: ^0.15.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  flutter_keyboard_visibility: ^6.0.0
  ffi: 2.1.0
  win32: 5.5.3
  http: 1.2.0
  dart_webrtc: ^1.4.6+hotfix.1
  webrtc_interface: 1.2.0
  flutter_webrtc: ^0.11.7
  #  flutter_webrtc_plus: ^0.11.2+5
  #  medea_flutter_webrtc: ^0.11.0
  protobuf: ^3.1.0
  analyzer: ^6.5.0
  provider: ^6.1.2
  flex_seed_scheme: ^3.1.2
  geolocator: ^13.0.1
  flutter_inappwebview: ^6.0.0
  connectivity_plus: ^6.0.2
  emoji_picker_flutter: ^3.0.0
  webview_flutter: ^4.9.0
  webview_all: ^0.4.1
  webf: ^0.16.1
  webview_flutter_android: ^3.13.1
  webview_flutter_wkwebview: ^3.10.0
  webview_flutter_web: ^0.2.2+3
  webview_flutter_platform_interface: ^2.9.0
  webview_win_floating: #2.0.0 #webView for
    git: https://github.com/jakky1/webview_win_floating.git
  flutter_widget_from_html: ^0.15.1
  sprintf: ^7.0.0
  flex_color_picker: ^3.5.0
  permission_handler: ^11.2.0
  file_picker: ^8.0.6
  shared_preferences: ^2.3.1
  intl: ^0.19.0
  image: ^4.0.12
  camera: ^0.11.0 #调用相机
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  full_picker: ^2.1.0
  image_cropper: ^8.0.1
  light_compressor: ^2.2.0
  collection: ^1.17.0
  path: ^1.8.3
  audio_video_progress_bar: ^2.0.1
  pdfx:
    git:
      url: 'https://github.com/ScerIO/packages.flutter'
      path: packages/pdfx
  pdf: ^3.10.4 #所有平台，创建pdf
  record: 5.1.2
  record_darwin: 1.1.0
  secure_application: ^4.0.1
  visibility_detector: ^0.4.0+2 #组建可见性的大小发生变化
  focus_detector: ^2.0.1 #组建在界面上消失或者出现
  image_picker: ^1.1.2 #选取图库,移动从图像廊或者相机选，桌面实现采用file_selector，从文件系统选
  markdown: ^7.1.1
  lottie: ^3.1.2
  flutter_quill: ^10.4.0
  flutter_quill_extensions: ^10.4.0
  saver_gallery: 3.0.1
  gal: ^2.3.0
  enough_mail: #^2.1.6
    git: https://github.com/Enough-Software/enough_mail.git
  enough_media: #^2.2.2
    git: https://github.com/enough-software/enough_media
  enough_mail_html: #^2.0.1
    git: https://github.com/Enough-Software/enough_mail_html.git
  enough_html_editor: #^0.0.5
    git: https://github.com/Enough-Software/enough_html_editor.git
  enough_platform_widgets: ^1.0.0
  #    git: https://github.com/Enough-Software/enough_platform_widgets
  enough_mail_flutter: #^2.1.0 #ios崩溃
    git: https://github.com/Enough-Software/enough_mail_flutter.git
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  analyzer: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/images/app1024.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/app1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app1024.png"
flutter_native_splash:
  background_image: "assets/images/splash_bg.png"
  image: assets/images/splash.png
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
    - assets/wasm/sqlite3.wasm
    - assets/locale/
    - assets/icons/
    - assets/images/
    - assets/images/bg/
    - assets/images/email/
    - assets/images/majiang/
    - assets/images/majiang/card/
    - assets/images/poke/
    - assets/medias/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
